%\VignetteEngine{knitr}
%\VignetteIndexEntry{in-silico cleavage of polypeptides}
%\VignetteKeyword{polypeptide, cleavage}
%\VignettePackage{cleaver}
\documentclass[12pt,a4paper,english]{scrartcl}
\usepackage{hyperref}
\usepackage[numbers]{natbib}

\newcommand{\cleaver}{\texttt{cleaver} }
\newcommand{\mailaddr}[1]{\href{mailto:#1}{\normalfont\texttt{#1}}}

\author{Sebastian Gibb%
  \thanks{\mailaddr{mail@sebastiangibb.de}}
}

\begin{document}

\title{In-silico cleavage of polypeptides using the \cleaver package}

\maketitle

\section*{Introduction}

\cleaver allows in-silico cleavage of polypeptide sequences. The cleavage rules
are taken from the
\href{http://web.expasy.org/peptide_cutter/peptidecutter_enzymes.html}{ExPASy
PeptideCutter tool}\citep{peptidecutter}.

\section*{Simple Example}

Loading the \cleaver package:
<<>>=
library("cleaver")
@

Cleaving of \emph{Gastric juice peptide 1} using \emph{Trypsin}:
<<>>=
cleave("LAAGKVEDSD", enzym="trypsin")
@

Sometimes cleavage is not perfect and the enzym miss some cleavage positions:
<<>>=
## miss one cleavage position
cleave("LAAGKVEDSD", enzym="trypsin", missedCleavages=1)

## miss zero or one cleavage positions
cleave("LAAGKVEDSD", enzym="trypsin", missedCleavages=0:1)
@

\section*{Insulin \& Somatostatin Example}

Downloading \emph{Insulin} and \emph{Somatostatin} sequences
from the \href{http://www.uniprot.org}{UniProt}\citep{uniprot} database:
<<>>=
id <- c(insulin="INS_HUMAN", somatostatin="SMS_HUMAN")
urls <- paste0("http://www.uniprot.org/uniprot/", id, ".fasta")

sequences <- sapply(urls, function(x) {
  f <- scan(x, what=character(), skip=1)
  return(paste0(f, collapse=""))
})
@

Cleaving using \emph{Pepsin}:
<<>>=
cleave(sequences, enzym="pepsin")
@

\bibliographystyle{plainnat}
\bibliography{cleaver}

\end{document}

\end{document}

